name: Shell Commands again

on: [push]

jobs: 
    task1:
        runs-on: ubuntu-latest
        steps:
            - name: step1
              run: echo "step1 executed"

            - name: step2
              run: ls

            - name: lets add python
              run: |
                  import platform
                  print(platform.processor())
              shell: python