name: Shell Commands again

on: [pull_request]

jobs: 
    task1:
        runs-on: ubuntu-latest
        
        steps:
            - name: step1
              run: echo "step1 executed"

            - name: step2
              run: ls

            - name: lets add python
              run: |
                  import platform
                  print(platform.processor())
              shell: python

    task2:
        runs-on: windows-latest
        needs: ["task1"]
        steps:
            - name: directory pw shell
              run: Get-Location

            - name: directory bash 
              run: pwd
              shell: bash
