name: listing files and getting the present working directory

on: [push]

jobs:
    listing_directory:
            runs-on: ubuntu-latest
            steps:
                  - name: listing_dir
                    run: |
                        pwd
                        ls