name: Cron schedule

on: 
    # schedule:
    #   - cron: "0/5 * * * *" #use crontab guru 1,2 within* or 1-3 or 0/15(steps)... NOTE: time in UTC
    #    #minimum workflow time is 5mins not less
    # # push:
    pull_request:
            types: [closed, opened,
                    reopened, assigned]

jobs: 
    run-shell-command:
        runs-on: ubuntu-latest
        steps: 
            - name: echo a string
              run: echo "hello"