name: Cron schedule

on: 
    schedule:
      - cron: "0/5 * * * *" #use crontab guru 1,2 within* or 1-3 or 0/15(steps)... NOTE: time in UTC
      - cron: "0/6 * * * *"
    # push:
    pull_request:
            types: [closed, opened,
                    reopened, assigned]

jobs:
    job_name:
    runs-on: ubuntu-latest
    steps:
        - name: 
          uses/run: