name: Env variables

on: push
env:
  WF_ENV: ${{secrets.WF_ENV}} #.GITHUB_TOKEN is by default generated if we want to use the github API


jobs:
    log-env:
      runs-on: ubuntu-latest
      env:
        JOB_ENV: job env only
      steps:
        - name: log env variables
          env: 
            STEP_ENV: step env only
          run: |
            echo "WF_ENV: ${WF_ENV}"
            echo "JOB_ENV: ${JOB_ENV}"
            echo "STEP_ENV: ${STEP_ENV}"
    