name: actions on branches

on: 
  push:
      branches: 
        - 'dev/experiment' 
        #branches-ignore ignores the listed branches
        #pattern matching ** for even /
        #tags: ; paths: can also be used and it'll find it within the repo
        # expceptions ! need to come after all non-exception patterns

jobs:
    for_dev_slash:
      runs-on: ubuntu-latest
      steps:
          - name: sanity_check
            run: echo "success"